// <auto-generated />
using System;
using Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Data.Entities.TaxBand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LowerLimit")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaxRate")
                        .HasColumnType("int");

                    b.Property<int?>("UpperLimit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TaxBands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7b3e6b6a-9a58-4b41-a815-3828a9f23f28"),
                            LowerLimit = 0,
                            Name = "Tax Band A",
                            TaxRate = 0,
                            UpperLimit = 5000
                        },
                        new
                        {
                            Id = new Guid("e7751ebc-1b20-48e1-9d67-d9fc58d06c4d"),
                            LowerLimit = 5000,
                            Name = "Tax Band B",
                            TaxRate = 20,
                            UpperLimit = 20000
                        },
                        new
                        {
                            Id = new Guid("f824c88c-6ff7-4dc5-b376-32c0c3fb2ba8"),
                            LowerLimit = 20000,
                            Name = "Tax Band C",
                            TaxRate = 40
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
